// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /v1/pet)
	GetPet(c *gin.Context)

	// (PUT /v1/pet)
	UploadPet(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetPet operation middleware
func (siw *ServerInterfaceWrapper) GetPet(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPet(c)
}

// UploadPet operation middleware
func (siw *ServerInterfaceWrapper) UploadPet(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UploadPet(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/v1/pet", wrapper.GetPet)
	router.PUT(options.BaseURL+"/v1/pet", wrapper.UploadPet)
}

type GetPetRequestObject struct {
}

type GetPetResponseObject interface {
	VisitGetPetResponse(w http.ResponseWriter) error
}

type GetPet200Response struct {
}

func (response GetPet200Response) VisitGetPetResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type GetPet204Response struct {
}

func (response GetPet204Response) VisitGetPetResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type UploadPetRequestObject struct {
}

type UploadPetResponseObject interface {
	VisitUploadPetResponse(w http.ResponseWriter) error
}

type UploadPet200Response struct {
}

func (response UploadPet200Response) VisitUploadPetResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type UploadPet400Response struct {
}

func (response UploadPet400Response) VisitUploadPetResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /v1/pet)
	GetPet(ctx context.Context, request GetPetRequestObject) (GetPetResponseObject, error)

	// (PUT /v1/pet)
	UploadPet(ctx context.Context, request UploadPetRequestObject) (UploadPetResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetPet operation middleware
func (sh *strictHandler) GetPet(ctx *gin.Context) {
	var request GetPetRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetPet(ctx, request.(GetPetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPet")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetPetResponseObject); ok {
		if err := validResponse.VisitGetPetResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// UploadPet operation middleware
func (sh *strictHandler) UploadPet(ctx *gin.Context) {
	var request UploadPetRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UploadPet(ctx, request.(UploadPetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UploadPet")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(UploadPetResponseObject); ok {
		if err := validResponse.VisitUploadPetResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZz0/jxhf/V0Zz9jcJaA9f+VT6QyvUqosKPay6HAZ7knjXnnFnxkC0QoJCd0F7oOqh",
	"IlqpODYqVw4IVmKL/xf/JdUbO46dOAlLt7dIIyWx37z3mc/7Me8pr3GXS4VN7HKLuPDd/H+r1cIGdlib",
	"Y/M1tjhTxFLwlXrEcbGJqR180SO24A2Le9jAgYCnXaV8aTab1A4axdum4/mBK2kT7xnYptISjq8czrCJ",
	"N7oUdThxEW8j1XUkUkS+QvDJkeP5LvUoU+iHb9Y30MraKiLMRutrK/DW4ttUINWlKNO4RW30zKcMxKRP",
	"LaftWASsNNAK66GnHLnOliCih7hAbcGZosxGbUE8usOFtkksi/qKbLm0gZ7zAHmkhwJJ0ehQjuKiIXdI",
	"p0NFw+GAwxd026E7GXow3MAGVo5yKTbxc6AArWbHRxtUKrRB5Cts4G0qZEZBq9FqLAEz3KeM+A42MTaw",
	"T1RXAt/N7aWmTzX1neyjyuBTqhDddaRyWAeBoFYk9NFX7UxgTT/2BbcDi0ps/oSJ77s5P82XkjO8aWBB",
	"pc+ZpNrscqs1aevZt9jA0upSj+hQ2CXgIvhKpOUA8jTcn7/iuStM44uZ62h8y2CWxRdsDqIoTOMkDc/T",
	"8L1eJ59vvU/j23Rw9Dhc8cd08FYD3H8Qs8Ua3Ew9aMFU9CGNLx+JK8lxAVm/DPVdpeHbCeGDh0E+S8PD",
	"Eq7k3+J6IE2h3nWVxjd6XcyKI3DGaSWEByNcUSkWPwkXhN5f1SdXuTCwkNF3koZ3IAYGQx2nVeXxJcAP",
	"E+2PfkHfC6Ytv9MK+vrlLaiJj6bgCudTVuOd4xxdJSWvhhl1UEFa+PGDzosxNcNk+QQ/npdw1W45nkjJ",
	"gzr3lOLrLI2SNH4zrgYe1uL6bdwj2bEgJK7TQTKK7HB6hNQL9DM+KnHfT6PbaqRqaHP5ij7m6VmO49zm",
	"fRr/qi0nU0BpgegY4BRG46QmH/sQhVksZE4ZwxVfTSuGdeSeQWSFSYnfMI3/SKPfhwVOm6sI7NfjKoUY",
	"0Hc/YepkZsRfTqmlpaMAO6c1YRAWwZDMr19/1/kxTAdvquVh+DO6A2iD/Zp8DLNydq2p6Q9/XqThn6ME",
	"iLRnw9P5uLSdyVt31tJlKCuqD92Y3e1ZIXs3t95DKJ2Xrlld/aK7YUToBTGVDAtjaWXCRVmMk9LzYRcQ",
	"3ek8KcrGQ++hqCiGF+ngPs9+4KLobe7HC8Zob1Ii63okViRm7rLDx92PNQXweFZhnC/WhyslvNFID6dt",
	"x3VtP+sRhiyioPX1BfSsysl6z7yZHO8+16hCfpfDZMDQyvpXq6uICIXaXHgE+lvPYd9R1lFdbC4ZWPV8",
	"6MClEg7rYAPv/o8FrgvNPTbbxJV0fBYZN/f16BdMJz5ViDM9cGgQjzC4Bz32z4EjqK17cH3MKorNQg/f",
	"ekkthWHTcuvJJLzvuYYU+C4nNrVRj2bCinR0hw+jwCZQG6h8gpOBN735ryr/UWtFjO7UjhTZ63yqIDBC",
	"KSpAda3LRr6FgRKbeIvbPWxgRjw4qE/VWllkRJESAV3MG4t5YzFvLOaNxbyxmDcW88Zi3ljMG4t5YzFv",
	"/JfzxuZn+qdgz8BP6l59SWwEsKisG1jgSf4HCzbxcqOF9/4JAAD//3fMJRqfGgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
